server:
  port: 8080
spring:
  cloud:
    consul:
      host: registry
      discovery:
        hostname: ${HOSTNAME:uat}
        prefer-ip-address: false

# Eureka Configuration
eureka:
  instance:
    hostname: ${HOSTNAME:uat}
  client:
    serviceUrl:
      defaultZone: http://registry:8761/eureka/

# MongoDB configuration
rp:
   mongo:
     uri: mongodb://mongodb:27017
     dbName: reportportal
#     user:
#     password:
