server:
  port: 9999
#security:
#  oauth2:
#    resource:
#      filter-order: 3
spring:
  jackson:
    default-property-inclusion: non_null
  session:
    store-type: jdbc
  datasource:
    driver-class-name: org.postgresql.Driver
    username: rpuser
    password: rppass
    url: jdbc:postgresql://localhost:5432/reportportal
  jpa:
    properties:
      hibernate.jdbc.lob.non_contextual_creation: true
      hibernate:
        dialect: com.epam.ta.reportportal.commons.JsonbAwarePostgresDialect

logging:
  level:
    org.springframework.security: debug

springfox:
  documentation:
    swagger:
      v2:
        path: /api-docs