server:
  port: 9999
security:
  sessions: stateless


spring:
  profiles:
    ## Default one is still Eureka
    active: ${rp.profiles:eureka}
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        tags:
          - urlprefix-${server.context-path:}
          - traefik.frontend.rule=PathPrefixStrip:${server.context-path:}
        healthCheckPath: ${server.context-path:}/health
        host-info: ${server.context-path:}/info
        ip-address: 10.200.10.1
        prefer-ip-address: true
      ## Disabled by default
      enabled: false
  # Redis Configuration
  redis:
    host: ${reportportal.redis.host:docker.local}
    port: 6379

  # Enable MongoDB repositories
  data:
    mongodb:
      repositories:
        enabled: true
  jackson:
    default-property-inclusion: non_null
  session:
    store-type: mongo


eureka:
  instance:
    hostname: ${HOSTNAME:localhost}
    status-page-url-path: ${server.contextPath:}/info
    health-check-url-path: ${server.contextPath:}/health
  ## Disabled by default
  client:
    register-with-eureka: false
    enabled: false

# MongoDB configuration
rp:
   session:
        live: 1800
   mongo:
        host: ${reportportal.mongo.host:localhost}
        port: 27017
        dbName: reportportal
#        user: user
#        password: 1q2w3e
        connectionsPerHost: 50
        threadsAllowedToBlockForConnectionMultiplier: 50
        connectTimeout: 20000
        socketTimeout: 60000
        maxWaitTime: 120000
        autoConnectRetry: true
        socketKeepAlive: true
        slaveOk: true
        writeTimeout: 0
        writeNumber: 1
        writeFsync: false
   cache:
        project:
          size: 1000
          expiration: 1
          info: 10
        ticket:
          size: 10000
          expiration: 5
        user:
          size: 1000
          expiration: 60

# GitHUB Oauth Configuration
github:
  client:
    clientId: f4cec43d4541283879c4
    clientSecret: a31aa6de3e27c11d90762cad11936727d6b0759e
    accessTokenUri: https://github.com/login/oauth/access_token
    userAuthorizationUri: https://github.com/login/oauth/authorize
    clientAuthenticationScheme: form
    scope: user
  resource:
    userInfoUri: https://api.github.com/user
logging:
  level: debug


## Consul as service registry
---
spring:
  profiles: eureka
  cloud:
    consul:
      enabled: false
      discovery:
        register: false
eureka:
  client:
    register-with-eureka: true
    enabled: true
## Consul as service registry
---
spring:
  profiles: consul
  cloud:
    consul:
      enabled: true
      discovery:
        register: true
eureka:
  client:
    register-with-eureka: false
    enabled: false
---
